sonar.host.url=http://localhost:9001
sonar.login=sqp_2aad31c251f792f94210a3ab2f974fac09284a0e
sonar.projectKey=Supermarket-sonar
sonar.projectName=Supermarket sonar
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.dependencyCheck.jsonReportPath=dependency-check-reports/dependency-check-report.json
sonar.dependencyCheck.htmlReportPath=dependency-check-reports/dependency-check-report.html
sonar.dependencyCheck.summarize=true
sonar.dependencyCheck.securityHotspot=true